### PR TITLE
footer

### PR DESCRIPTION
**Pull request by olive-lavine**
You currently have to scroll to see the footer bc of styling issues. I could work around it by rendering the footer directly in the Landing Page and State pages and adjusting the padding, but will try again tomorrow to find a better solution. Pushing the changes so you can see how the logos/links look in the meantime!

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
Awesome

**Comment by olive-lavine** [comment]
Hi, are you okay with me pushing as is? I made a little adjustment so you
don't have to scroll on the landing page but can iterate on it later!

**Comment by olive-lavine** [comment]
Also I added a separate legal disclaimer modal before I saw your update in
the about modal. Let me know where you think is better and I'll adjust.

**Review by ayyubibrahimi — APPROVED** [review]
Yes! Go for it.

**Pull request merged**
